# Generated by Django 3.1.4 on 2020-12-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WildLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(default='animal', max_length=20)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='pics')),
                ('article', models.TextField()),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
