# Generated by Django 3.1.4 on 2020-12-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlife',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='pics'),
        ),
    ]
