# Generated by Django 3.1.4 on 2021-01-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_wildlife_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlife',
            name='json',
        ),
    ]
