# Generated by Django 3.1.4 on 2021-01-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210103_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlife',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='pics'),
        ),
    ]
